name: RecSys
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pip
  - pytorch-cuda=12.1
  - pytorch=2.2.1
  - torchvision=0.17.1
  - torchaudio=2.2.1
  - datasets
  - transformers
  - sentencepiece
  - protobuf
  - wandb