name: RecSys
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pip
  - pytorch-cuda=12.1
  - pytorch=2.2.1
  - torchvision=0.17.1
  - torchaudio=2.2.1
  - datasets=2.19.2
  - transformers=4.41.2
  - sentencepiece=0.2.0
  - protobuf=5.27.1