wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.1
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717854532
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 100
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 100
      3:
      - 23
      4: 3.11.9
      5: 0.17.1
      6: 4.41.2
      8:
      - 5
      13: linux-x86_64
